### ISSUE TITLE
gradle about plugin 0.2 and 0.2-SNAPSHOT fails if was started using about.execute() in jar.doLast

### ISSUE THREAD

**Issue by aleskovets** [evgeny-goldin/gradle-plugins#4]
I am running about plugin as a lat thing after jar task using tasks.about.execute():

``` groovy
jar.doLast {
    logger.lifecycle(":${project.name}:about")
    try {
        tasks.about.execute()
    } catch (Exception e) {
        logger.error("Failed to gather project info", StackTraceUtils.extractRootCause(e))
    }
}
```

it worked fine in 0.1.3, but fails in 0.2:

```
:model:compileJava UP-TO-DATE
:model:processResources UP-TO-DATE
:model:classes UP-TO-DATE
:model:jar
:model:about
Failed to gather project info: 
org.gradle.api.GradleException: The following tasks have not been executed yet: ':model:jar'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
    at com.github.goldin.plugins.gradle.about.AboutTask.archivesToUpdate(AboutTask.groovy:44)
    at com.github.goldin.plugins.gradle.about.AboutTask.taskAction(AboutTask.groovy:21)
    at com.github.goldin.plugins.gradle.common.BaseTask.doTask(BaseTask.groovy:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1047)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:877)
    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:216)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:122)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
    at com.github.goldin.plugins.gradle.about.AboutTask_Decorated.invokeMethod(Unknown Source)
    at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
    at org.gradle.util.ReflectionUtil.invoke(ReflectionUtil.groovy:23)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:161)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:156)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:472)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:461)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:60)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:34)
    at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter$1.run(CacheLockHandlingTaskExecuter.java:34)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:169)
    at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:232)
    at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDirectoryStore.java:138)
    at org.gradle.api.internal.changedetection.DefaultTaskArtifactStateCacheAccess.longRunningOperation(DefaultTaskArtifactStateCacheAccess.java:83)
    at org.gradle.api.internal.changedetection.CacheLockHandlingTaskExecuter.execute(CacheLockHandlingTaskExecuter.java:32)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:55)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:41)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:42)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:247)
    at org.gradle.api.internal.AbstractTask.execute(AbstractTask.java:242)
    at org.gradle.api.internal.TaskInternal$execute.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at build_16i8v57fk90715667jtaeqh1np$_run_closure6_closure15.doCall(build.gradle:127)
...
```

**Comment by aleskovets** [comment]
Actually I cannot use 0.2 at all - even `gradle build about` throws the same error

**Comment by evgeny-goldin** [comment]
Usually, I use it as

```
defaultTasks 'clean', 'build', 'about'
```

since direct task invocation is never a recommended approach. I've just added a `failOnError` boolean flag (`true` by default) which you can set to `false` to avoid the try/catch.

In this new version there's no need to specify a directory + include/exclude file patterns (although they're still supported). One can use

```
about {
    tasks       = [ jar ]
    failOnError = false
}
```

to specify a list of Zip tasks which artifacts should be updated. By default all project's Zip-tasks are assumed to be updated and for each such task (whether specified explicitly with 'tasks' or for all possible found) it is verified the task has executed already to ensure its artifacts are available. In your case the error says task 'jar' hasn't run for the 'model' module which makes sense since the 'about' task was fired before 'jar' has actually completed.

**Comment by evgeny-goldin** [comment]
To stop using Zip-tasks update and go back to the old behavior of `directory` and `include`/`exclude` patterns set a `zipTasks` boolean flag to `false`.

**Comment by aleskovets** [comment]
Thanks. `zipTasks = false` did the trick.

**Comment by evgeny-goldin** [comment]
Good! But try switching to Zip tasks from matching archive files in a directory, this will ensure any artifact ever created by your project will be updated.

**Comment by aleskovets** [comment]
I am not sure how to use zip tasks in the case when I need to add about files to each submodule and root project (basically in META-INF folders in war and jars) while building root project. Such approach may be useful as we are using exploded archives in some environments and theoretically modules could be updated independently.

**Comment by evgeny-goldin** [comment]
That's what I used in a [multi-project build](https://github.com/evgeny-goldin/gradle-plugins-test/blob/2108168d41267752026e7a9f5abef9954ea4bf10/build.gradle#L108):

```
about {
    includeEnv          = true
    includeSystem       = true
    includeProperties   = true
    includePaths        = true
    includeDependencies = [ 'compile', 'runtime' ]
    tasks               = p.tasks.toList().findAll{ Task t -> t instanceof Zip }
}
```

So it's all about filtering out the corresponding tasks available at the moment `about{ .. }` is configured. Here's a way to print out all Zip tasks in a project:

```
gradle.taskGraph.whenReady {
    println "Zip tasks: ${ project.rootProject.subprojects*.tasks*.toList().flatten().findAll{ Task t -> t instanceof Zip }}"    
}
```

**Comment by evgeny-goldin** [comment]
Or, [alternatively](https://github.com/evgeny-goldin/gradle-plugins-test/blob/78225083ac7957b44ffcc4e2cbc05d734d351d10/build.gradle#L108):

```
about {
    ...
    tasks = p.tasks.withType( Zip ).toList() // That's what happens by default
}

gradle.taskGraph.whenReady {
    println "Zip tasks: ${ project.rootProject.subprojects*.tasks*.withType( Zip ).flatten()}"    
}
```
